language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t raduterec/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true raduterec/docker-react npm run test